# Generated by Django 3.1.5 on 2021-02-14 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auto_20210213_2006"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="author",
        ),
    ]
