# Generated by Django 5.0 on 2023-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_user_is_reporter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
