# Generated by Django 3.1.4 on 2020-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_dative', models.CharField(max_length=100)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
