# Generated by Django 3.1.5 on 2021-02-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='death_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
