# Generated by Django 3.1.5 on 2021-02-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_author_death_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_year',
            new_name='year_born',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='death_year',
            new_name='year_dead',
        ),
    ]
