# Generated by Django 3.1.5 on 2021-02-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poem", "0004_auto_20210213_2026"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
