# Generated by Django 3.1.5 on 2021-02-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0008_auto_20210214_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name', 'year_born']},
        ),
    ]
