# Generated by Django 3.1.5 on 2021-03-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poem", "0012_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="publicly_visible",
            field=models.BooleanField(default=False),
        ),
    ]
