# Generated by Django 3.2.5 on 2021-08-09 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poem", "0017_alter_poem_editorial_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poem",
            options={"ordering": ["-editorial_status", "-editorial_timing"]},
        ),
    ]
